"""
report_gen.py — Generate a unified Markdown report from all output files.

Collects data from subdomains.txt, live_hosts.txt, port_scan.json,
dir_enum.json, nuclei_results.json, and cve_mapping.json, and
produces a single report.md with clearly formatted sections and tables.
"""

import os
import json
from modules.utils import Logger

def load_text(path):
    if not os.path.isfile(path):
        return []
    with open(path, "r") as f:
        return [line.strip() for line in f if line.strip()]

def load_json(path):
    if not os.path.isfile(path):
        return None
    with open(path, "r") as f:
        try:
            return json.load(f)
        except json.JSONDecodeError:
            Logger.warning(f"Could not parse JSON from {path}")
            return None

def run(cfg):
    Logger.stage("Generating Report")

    output_dir = cfg["output_dir"]
    report_path = os.path.join(output_dir, "report.md")
    target = "TARGET"  # Could be passed from main, but we'll just note it's an overview
    sub_file = os.path.join(output_dir, "subdomains.txt")
    live_file = os.path.join(output_dir, "live_hosts.txt")
    port_file = os.path.join(output_dir, "port_scan.json")
    dir_file = os.path.join(output_dir, "dir_enum.json")
    nuclei_file = os.path.join(output_dir, "nuclei_results.json")
    cve_file = os.path.join(output_dir, "cve_mapping.json")

    subs = load_text(sub_file)
    live = load_text(live_file)
    ports = load_json(port_file)
    dirs = load_json(dir_file)
    nuclei = load_text(nuclei_file)   # nuclei results are newline-delimited JSON
    cves = load_json(cve_file)

    # Build Markdown
    md = []
    md.append("# ReconForge Assessment Report")
    md.append("")
    md.append(f"**Target:** `{target}`")
    md.append(f"**Date:** (generated by Vulnsweep)")
    md.append("")

    # Subdomains
    md.append("## Subdomains Found")
    if subs:
        md.append(f"Total: {len(subs)}")
        md.append("```")
        for s in subs:
            md.append(s)
        md.append("```")
    else:
        md.append("No subdomain data available.")
    md.append("")

    # Live Hosts
    md.append("## Live Hosts")
    if live:
        md.append("| URL | Status Code | Title |")
        md.append("|-----|-------------|-------|")
        for line in live:
            parts = line.split()
            url = parts[0] if parts else "-"
            status = parts[1] if len(parts) > 1 else "-"
            # Title may contain spaces, join remaining parts
            title = " ".join(parts[2:]) if len(parts) > 2 else "-"
            md.append(f"| {url} | {status} | {title} |")
    else:
        md.append("No live host data.")
    md.append("")

    # Open Ports & Services
    md.append("## Open Ports & Services")
    if ports:
        for host in ports:
            md.append(f"### {host['host']}")
            if host["ports"]:
                md.append("| Port | Service | Product | Version |")
                md.append("|------|---------|---------|---------|")
                for p in host["ports"]:
                    port = p["port"]
                    service = p["service"]
                    product = p.get("product", "-")
                    version = p.get("version", "-")
                    md.append(f"| {port} | {service} | {product} | {version} |")
            else:
                md.append("No open ports detected.")
    else:
        md.append("No port scan data.")
    md.append("")

    # Directory enumeration
    md.append("## Directories/Files Found")
    if dirs:
        for url, entries in dirs.items():
            md.append(f"### {url}")
            if entries:
                md.append("| Path | Status | Size |")
                md.append("|------|--------|------|")
                for entry in entries:
                    path = entry.get("url", "-")
                    status = entry.get("status", "-")
                    size = entry.get("length", "-")
                    md.append(f"| {path} | {status} | {size} |")
            else:
                md.append("No directories/files discovered.")
    else:
        md.append("No directory enumeration data.")
    md.append("")

    # Vulnerabilities
    md.append("## Vulnerabilities Found")
    if nuclei:
        vuln_list = []
        for line in nuclei:
            try:
                vuln_list.append(json.loads(line))
            except json.JSONDecodeError:
                pass
        if vuln_list:
            md.append("| Name | Severity | Host | Matched At |")
            md.append("|------|----------|------|------------|")
            for v in vuln_list:
                info = v.get("info", {})
                name = info.get("name", "Unknown")
                severity = info.get("severity", "info")
                host = v.get("host", "-")
                matched = v.get("matched-at", "-")
                md.append(f"| {name} | {severity} | {host} | {matched} |")
        else:
            md.append("No vulnerabilities detected.")
    else:
        md.append("No vulnerability scan data.")
    md.append("")

    # CVE Details
    md.append("## CVE Details")
    if cves:
        md.append("| CVE ID | CVSS Score | Severity | Vector |")
        md.append("|--------|------------|----------|--------|")
        for item in cves:
            cve_id = item["cve"]
            score = item.get("score", "N/A")
            severity = item.get("severity", "N/A")
            vector = item.get("vector", "")
            md.append(f"| {cve_id} | {score} | {severity} | {vector} |")
    else:
        md.append("No CVE mapping data.")
    md.append("")

    md.append("---")
    md.append("*Report generated by Vulnsweep - authorized testing only.*")

    with open(report_path, "w", encoding="utf-8") as f:
        f.write("\n".join(md) + "\n")
    Logger.success(f"Report written -> {report_path}")